name: ArenaAndFFAManager
version: '0.0.1'
main: me.molfordan.arenaAndFFAManager.ArenaAndFFAManager
api-version: '1.8'
softdepend:
  - PlaceholderAPI
commands:
  arenamap:
    usage: '/arenamap <create|pos1|pos2|finish|remove> <name>'
    description: 'ArenaFFAManager'
    permission: arenamap.admin
  arenabypass:
    usage: '/arenabypass'
    description: 'Arena bypass'
    permission: arenamap.admin
  commandbypass:
    usage: '/commandbypass'
    description: 'Command bypass'
    permission: arenamap.admin
  arenaconfig:
    usage: '/arenaconfig reload'
    description: 'Arena config reload'
    permission: arenamap.admin
  setlobby:
    usage: '/setlobby'
    description: 'sets a lobby'
    permission: arenamap.admin
  build:
    usage: '/build'
    description: 'Build Mode'
    permission: arenamap.admin
  buildffa:
    usage: '/buildffa'
    description: 'buildffa'
  bridgefight:
    usage: '/bridgefight'
    description: 'bridgefight'
  loadworld:
    usage: '/loadworld <name> <type>'
    description: 'load worlds'
  spawn:
    usage: '/lobby'
    description: 'lobby'
  setpos1:
    usage: '/setpos1 <platform>'
    description: 'setpos1'
  setpos2:
    usage: '/setpos2 <platform>'
    description: 'setpos2'
  rc:
    usage: '/rc'
    description: 'region command'
  hotbarmanager:
    description: 'open hotbarmanager'
    usage: '/hotbarmanager'
    aliases: [hbm]
  stats:
    usage: '/stats <player>'
    description: 'stats command'
  leaderboard:
    usage: '/leaderboard'
    description: 'leaderboard command'
  guistats:
    usage: '/guistats <player>'
    description: 'guistats command'
  bridgeban:
    usage: '/bridgeban <player> [duration] [reason]'
    description: 'bridgeban command'
  bridgeunban:
    usage: '/bridgeunban <player> [reason]'
    description: 'bridgeunban command'
  guileaderboard:
    usage: '/guileaderboard'
    description: 'guileaderboard command'
  playerhistory:
    usage: '/playerhistory <player>'
    description: 'playerhistory command'
  freeze:
    usage: '/freeze <player>'
    description: 'frozen command'
    aliases: [frozen, ss]
  unfreeze:
    usage: '/unfreeze <player>'
    description: 'unfrozen command'
    aliases: [unfrozen, unss]
  report:
    usage: '/report <player> <reason>'
    description: 'report command'
  reports:
    usage: '/reports <page>'
    description: 'reports command'

permissions:
  arenamap.admin:
    description: 'ArenaFFAManager'
